MudName         Neolith RO

Port            5001:telnet

MudlibDir       /home/tiny/neolith/mudlib_ro
LogDir          /home/tiny/neolith/mudlib_ro/log

DebugLogFile    debug.log
LogWithDate     yes

CrashDropCore   No

IncludeDir      /include

MasterFile      /adm/obj/master.c
SimulEfunFile   /adm/obj/simul_efun.c

DefaultErrorMsg Error occurred.
DefaultFailMsg  What?

CleanupDuration 600
ResetDuration   1800

MaxInheritDepth 30
MaxEvaluationCost 1000000
MaxArraySize    15000
MaxMappingSize  15000
MaxBufferSize   400000
MaxStringLength 200000

MaxByteTransfer 10000
MaxReadFileSize 200000

SharedStringHashSize 20011
ObjectHashSize 10007

StackSize       1000
MaxLocalVariables 25
MaxCallDepth    50

ArgumentsInTrace Yes
LocalVariablesInTrace Yes

# Preload files
Preload         /adm/etc/preload

# RO Login Server Port (Binary Protocol)
Port            6900:binary
